grpc_services:
  - name: notification
    server_address: "localhost:50051"
    timeout: 30s
    max_retries: 3
    keep_alive:
      time: 10s
      timeout: 20s
      permit_without_stream: true
  
  - name: user_service
    server_address: "localhost:50052"
    timeout: 15s
    max_retries: 2
    keep_alive:
      time: 5s
      timeout: 10s
      permit_without_stream: true
  
  - name: payment_service
    server_address: "localhost:50053"
    timeout: 45s
    max_retries: 5
    keep_alive:
      time: 15s
      timeout: 30s
      permit_without_stream: false
